### PR TITLE
frontend_init

### LINKED ISSUE #12: Set up UI framework based on the wireframe in Flutter
We need to set up flutter project with the atomic UI component built.

This flutter project will need to be set up so it can be web app and mobile app

Wireframe progress

https://www.figma.com/file/p4gfqRDn3ma4zPaPAj8vH4?node-id=0:1&locale=en&type=design

### PR DESCRIPTION
**Pull request by Rutik7066**
Hey @hsb1007 ,

I've kicked off the Flutter repo and sent a PR to lay the groundwork for our project's atomic UI components. Drawing from my four years of Flutter experience, I'm excited to contribute! Mind granting access to the Figma file? It'll help align our UI smoothly.

Also, could you kindly assign me this issue? It seems like a substantial task, and I'm eager to tackle it head-on.

Looking forward to your reply!

/closes #12
/claim #12
/claim #32

### CODE REVIEW

**Comment by Rutik7066** [comment]
Hi @hsb1007 I have updated current folder due to FOMO. I would need some details about project requirements such do will we  have web (landing pages, etc) and app (core app) separate ?

**Comment by Rutik7066** [comment]
localhost_45799_(iPhone XR)
As suggested in issue added atoms widget in PR

**Comment by hsb1007** [comment]
@Rutik7066 For #32 I could merge this PR for now and you can continue with the rest of component in Figma?

Let me know your thoughts!

**Comment by Rutik7066** [comment]
@hsb1007 I guess it is the molecule part on the atomic design pattern

> image image image image
> Hi @Rutik7066 I still see alot more other component from the Figma!
> 
> Can you please look into this?

**Comment by hsb1007** [comment]
Hi @Rutik7066 Thanks for sharing it, but my expectation was to at least have UI components ready so that ongoing page development becomes just assembling if you know what I mean and the reward price also reflects it..

**Comment by Rutik7066** [comment]
I would need some help to create the components from the designer.  I will work on it and i will like to attempt #32 as well. would it be okay for you ?

**Comment by hsb1007** [comment]
> I would need some help to create the components from the designer. I will work on it and I would like to attempt #32 as well. would it be okay for you ?

Hi Rutik

Let me know what you need from the designer! 

No worries, you can do #32.  Could you priortise #32 as you do this issue please?

So that the project can make progress?

Thank you Rutik! ANd please join Discord channel!

**Comment by Rutik7066** [comment]
Sure, no problem I will complete #32  and then complete the remaining. I don't see any discord link in your algora profile. could you please provide me the link?

**Comment by Rutik7066** [comment]
@hsb1007 I need to know which icon pack designers have used.

**Comment by Rutik7066** [comment]
@hsb1007 please check here I have done all components in last commit

**Comment by Rutik7066** [comment]
localhost_40803_
localhost_40803_ (1)

**Comment by Rutik7066** [comment]
localhost_41417_
localhost_41417_(iPhone XR)
localhost_41417_ (1)

**Comment by Rutik7066** [comment]
https://github.com/eronka/culero-api/assets/58112334/052ab51f-1cac-406d-b501-57a535bbec72

Hi @hsb1007 I apologize for the late, I have submitted the demo video. please let me know your thoughts.
hope you will reopen #12 and #32 and merge this PR. I have completed all the tasks.

**Comment by hsb1007** [comment]
@Rutik7066  Thank you for the work. could you do me a favour. 

Could you create this PR in below repo? we are separating backend and frontend!

https://github.com/eronka/culero-client/

**Comment by Rutik7066** [comment]
@hsb1007 sure I will do it. Will I get the reward for both #32 and #12.

**Comment by hsb1007** [comment]
> @hsb1007 sure I will do it. Will I get the reward for both #32 and #12.

Yup will review and reward if all good! thank you for your work!

**Comment by Rutik7066** [comment]
> > @hsb1007 sure I will do it. Will I get the reward for both #32 and #12.
> 
> Yup will review and reward if all good! thank you for your work!

i am doing it need some time to configuration. may be an hour.

**Comment by Rutik7066** [comment]
Hi @hsb1007 please review and let me you if you need some thing

**Comment by Rutik7066** [comment]
Hi @hsb1007 have you checked the PR raised at https://github.com/eronka/culero-client/

**Comment by Rutik7066** [comment]
Hi @hsb1007 can you comment on that pr ?

**Pull request closed without merging**
